/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javamedia_RTPTransmitAndroid */

#ifndef _Included_javamedia_RTPTransmitAndroid
#define _Included_javamedia_RTPTransmitAndroid
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javamedia_RTPTransmitAndroid
 * Method:    init_RTP
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_javamedia_RTPTransmitAndroid_init_1RTP
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     javamedia_RTPTransmitAndroid
 * Method:    Sender
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_javamedia_RTPTransmitAndroid_Sender
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
