/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_javamedia_NativeHandler */

#ifndef _Included_com_javamedia_NativeHandler
#define _Included_com_javamedia_NativeHandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_javamedia_NativeHandler
 * Method:    nativeReceiver_init
 * Signature: (Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_com_javamedia_NativeHandler_nativeReceiver_1init
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    nativeReceiver_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_javamedia_NativeHandler_nativeReceiver_1start
  (JNIEnv *, jclass);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    nativeReceiver_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_javamedia_NativeHandler_nativeReceiver_1stop
  (JNIEnv *, jclass);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    Get_throughput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_javamedia_NativeHandler_Get_1throughput
  (JNIEnv *, jclass);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    Get_throughput2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_javamedia_NativeHandler_Get_1throughput2
  (JNIEnv *, jclass);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    Decoder_release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_javamedia_NativeHandler_Decoder_1release
  (JNIEnv *, jclass);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    get_W
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_javamedia_NativeHandler_get_1W
  (JNIEnv *, jclass);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    get_H
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_javamedia_NativeHandler_get_1H
  (JNIEnv *, jclass);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    get_FrameQueue_C
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_javamedia_NativeHandler_get_1FrameQueue_1C
  (JNIEnv *, jclass);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    Get_streamedSegment
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_javamedia_NativeHandler_Get_1streamedSegment
  (JNIEnv *, jclass);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    Get_streamedSegment_tatol
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_javamedia_NativeHandler_Get_1streamedSegment_1tatol
  (JNIEnv *, jclass);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    get_a_DecodedFrame
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_javamedia_NativeHandler_get_1a_1DecodedFrame
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_javamedia_NativeHandler
 * Method:    get_a_Decoded_jumped_Frame
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_javamedia_NativeHandler_get_1a_1Decoded_1jumped_1Frame
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
